- Scripts/Scenes/Utils/UITemplateBasePresenter.cs
> fix creative

- Scripts/ThirdPartyServices/AnalyticEvents/Crazylab.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Crazylab/CrazylabAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Crazylab/CrazylabAnalyticEventFactory.cs.meta
> add symbol crazylab

- Scripts/Services/CountryFlags/CountryFlags/Scripts/CountryFlags.cs
> make some func to static in CountryFlags.cs

- Prefabs/VFXs/fx_combo/material/fx_star_s_blurry_green.mat
- Prefabs/VFXs/fx_combo/material/fx_star_s_blurry_red.mat
> fix missing texture

- Scripts/Installers/UITemplateAdsInstaller.cs
- Scripts/Scenes/EndGame/UITemplateLoseOP2Screen.cs
- Scripts/Scenes/EndGame/UITemplateWinOP2Screen.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
- Scripts/ThirdPartyServices/UITemplateAutoHideMRECService.cs
- Scripts/ThirdPartyServices/UITemplateAutoHideMRecService.cs.meta
> Duymai/native game/auto hide mrec

- Scripts/Leaderboard/Models/UITemplateLeaderBoardData.cs
- Scripts/Leaderboard/Models/UITemplateLeaderBoardDataController.cs
> change leaderboard key from object to string

- Scripts/Scenes/Loading/UITemplateLoadingScreenView.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> update function set position and size of banner

- Scripts/Quests/Data/UITemplateQuestBlueprint.cs
> fix quest blueprint

- Scripts/Quests/Conditions/Bases/BaseSignalCountCondition.cs
- Scripts/Quests/UITemplateQuestNotificationView.cs
> fix BaseSignalCountCondition

- Scripts/Quests/Prefabs/UITemplateQuestChestItemView.prefab.meta
- Scripts/Quests/Prefabs/UITemplateQuestListItemView.prefab
- Scripts/Quests/Prefabs/UITemplateQuestListItemView.prefab.meta
- Scripts/Quests/Prefabs/UITemplateQuestNotificationView.prefab.meta
- Scripts/Quests/Prefabs/UITemplateQuestPopupView.prefab
- Scripts/Quests/Prefabs/UITemplateQuestPopupView.prefab.meta
- Scripts/Quests/UI/Chest/UITemplateQuestChestView.cs
- Scripts/Quests/UI/List/UITemplateQuestListView.cs
> hide unused ChestView in QuestPopupView

- Scripts/Quests/UI/List/UITemplateQuestListItemAdapter.cs
- Scripts/Quests/UI/List/UITemplateQuestListItemAdapter.cs.meta
- Scripts/Quests/UI/List/UITemplateQuestListItemView.cs
- Scripts/Quests/UI/List/UITemplateQuestListView.cs
- Scripts/Quests/UI/UITemplateQuestPopupView.cs
> fix quest popup view

- Scripts/Installers/UITemplateInstaller.cs
- Scripts/Services/LockInputService.cs
- Scripts/Services/LockInputService.cs.meta
> lock input service

- Scripts/Scenes/Main/DailyReward/UITemplateDailyRewardItemView.cs
> if reward value = -1 then not display the value

- Scripts/HighScore/Signals/NewHighScoreSignal.cs
- Scripts/HighScore/UITemplateHighScoreDataController.cs
> add high score data controller doc

- Scripts/Quests/UI/List/UITemplateQuestListItemView.cs
- Scripts/Quests/UI/List/UITemplateQuestListView.cs
> upd: sound when claim quest

- Scripts/Installers/UITemplateInitSignalInstaller.cs
- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
- Scripts/Signals/OnNotEnoughCurrencySignal.cs
- Scripts/Signals/OnNotEnoughCurrencySignal.cs.meta
> add not enough currency signal

- Scripts/Scenes/BottomBarNavigator/UITemplateBottomNavigatorBarView.cs
> fix button

- Scripts/Scenes/BadgeNotify/UITemplateBadgeNotifySystem.cs
> update logic for badge notify system

- Scripts/Models/Controllers/UITemplateDailyRewardController.cs
- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
- Scripts/Quests/Prefabs/UITemplateQuestNotificationView.prefab
- Scripts/Quests/UITemplateQuestNotificationView.cs
- Scripts/Scenes/Main/DailyReward/UITemplateDailyRewardPopupView.cs
> Hungnh/native game/fix sound quest currency

- Scripts/HighScore/Models/UITemplateHighScoreData.cs
- Scripts/HighScore/UITemplateHighScoreDataController.cs
> add top user score

- Scripts/FTUE/UITemplateFTUEController.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> update ftue system

- Scripts/FTUE/UITemplateFTUEController.cs
> update ftue controller

- Scripts/FTUE/FTUEListen/FTUEBaseListen.cs
- Scripts/FTUE/FTUEListen/FTUEListenScreenShow.cs
- Scripts/FTUE/UITemplateFTUEController.cs
> update ftue system logic

- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Configs/GameEvents/QuestSystemConfig.cs
- Scripts/Configs/GameEvents/QuestSystemConfig.cs.meta
- Scripts/Installers/UITemplateInstaller.cs
- Scripts/Quests/UI/List/UITemplateQuestListItemView.cs
- Scripts/Quests/UI/List/UITemplateQuestListView.cs
- Scripts/Quests/UITemplateQuestInstaller.cs
- Scripts/Quests/UITemplateQuestNotificationView.cs
> add symbol & config for quest system

- Scripts/Quests/Prefabs/UITemplateQuestPopupView.prefab
> update reference of UITemplateQuestPopupView.prefab

- Scripts/Scenes/BadgeNotify/UITemplateBadgeNotifySystem.cs
> refactor code

- Scripts/Scenes/Loading/UITemplateLoadingScreenView.cs
> add showing loading percent

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
> add get set for last unlock reward

- Prefabs/NavigationBottomBar/UITemplateBottomNavigatorBarButton.prefab
- Scripts/Scenes/BottomBarNavigator/BottomBarNavigatorTabButtonView.cs
- Scripts/Scenes/BottomBarNavigator/UITemplateBottomNavigatorBarView.cs
> add callback when show bot navigation bar button, add lock icon

- Scripts/Services/RewardHandle/UITemplateRewardHandler.cs
> add reward flying animation when receive reward

- Prefabs/DailyReward/UITemplateDailyrewardPopupView.prefab
- Scripts/Services/UITemplateDailyRewardService.cs
make custom screen type
</p>
UI Template
</h1>
> update prefab reference,

- Scripts/Services/UITemplateDailyRewardService.cs
> update daily reward check first open time condition

- Scripts/ThirdPartyServices/AnalyticEvents/Zitga.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/ZitgaAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/ZitgaAnalyticEventFactory.cs.meta
</p>
UI Template
</h1>
Add zitga analytic event factory
> add zitga analytic event factory

- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/FirstOpenEvent.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/FirstOpenEvent.cs.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/ZitgaAnalyticEventFactory.cs
> update zitga event analytic factory

- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/ZitgaAnalyticEventFactory.cs
> update zitga analytic event factory

- Prefabs/NativeAds.meta
- Prefabs/NativeAds/NativeAdsView.prefab
- Prefabs/NativeAds/NativeAdsView.prefab.meta
> add prefab native ads

- Scripts/Others/StateMachine/Controller/StateMachine.cs
> make signalbus from game state machine inheritable

- Prefabs/UITemplateBlendButtonSettingPopupView.prefab
- Prefabs/UITemplateBlendButtonSettingPopupView.prefab.meta
- Scripts/Scenes/Popups/UITemplateBlendButtonSettingPopupView.cs
- Scripts/Scenes/Popups/UITemplateBlendButtonSettingPopupView.cs.meta
- Scripts/Scenes/Utils/UITemplateBlendButton.cs
- Scripts/Scenes/Utils/UITemplateBlendButton.cs.meta
> Add blend setting popup view

- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Configs/GameEvents/NoInternetConfig.cs
- Scripts/Configs/GameEvents/NoInternetConfig.cs.meta
- Scripts/Configs/GameEvents/RateUsConfig.cs
- Scripts/Configs/GameEvents/RateUsConfig.cs.meta
- Scripts/Installers/UITemplateInstaller.cs
- Scripts/Services/UITemplateNoInternetService.cs
- Scripts/Services/UITemplateNoInternetService.cs.meta
- Scripts/Services/UITemplateRateUsService.cs
- Scripts/Services/UITemplateRateUsService.cs.meta
> Config for Rate Us and No Internet in Game Feature Config

- Scripts/Scenes/Utils/UITemplateBlendButton.cs
> Blend duration now can be configurable

- Prefabs/RemoveAds/UITemplateRemoveAdsPopup.prefab
- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Configs/GameEvents/IAPConfig.cs
- Scripts/Configs/GameEvents/IAPConfig.cs.meta
- Scripts/Scenes/RemoveAds/UITemplateRemoveAdPopupView.cs
> Done ads remove popup

- Scripts/ThirdPartyServices/AnalyticEvents/Falcon/FalconAnalyticWrapper.cs
> add THEONE_IAP symbol

- Scripts/Scenes/RemoveAds/UITemplateRemoveAdsBottomBarView.cs
> hide no ads bottom bar in CREATIVE mode

- Scripts/Utils/MainCameraUtils.cs
- Scripts/Utils/MainCameraUtils.cs.meta
> add camera utils

- Scripts/Configs/GameEvents/RateUsConfig.cs
- Scripts/Services/UITemplateRateUsService.cs
> Add interval and only show once per session

- Scripts/FTUE/UITemplateFTUEControlElement.cs
- Scripts/FTUE/UITemplateFTUEController.cs
> make hand always stay on highlight object

- Scripts/Scenes/Utils/UITemplateBlendButton.cs
> Ignore timescale for BlendButtons

- Scripts/Quests/Signals/ClaimAllQuestSignal.cs
- Scripts/Quests/Signals/ClaimAllQuestSignal.cs.meta
- Scripts/Quests/UI/List/UITemplateQuestListItemView.cs
- Scripts/Quests/UI/UITemplateQuestPopupView.cs
- Scripts/Quests/UITemplateQuestInstaller.cs
> add claim all feature on quest popup

- Scripts/Creative/NewCreativeService.cs
- Scripts/Extension/UITemplateExtension.cs
- Scripts/FTUE/UITemplateFTUEController.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
- Scripts/UITemplate.Scripts.asmdef
> Implement R3

- Scripts/Leaderboard/PlayFabLeaderboard.cs
> allow players send request to view their locations

- Scripts/Leaderboard/PlayFabLeaderboard.cs
> add method to external get country code of play

- Scripts/Leaderboard/PlayFabLeaderboard.cs
> add api to get leaderboards' players data

- Scripts/Scenes/RemoveAds/UITemplateRemoveAdPopupView.cs
- Scripts/Scenes/RemoveAds/UITemplateRemoveAdsBottomBarView.cs
> update access modifier

- Editor/ProjectMigration/ApplovinMigration.cs
> add APPLOVIN symbol to ApplovinMigration

- link.xml
> fix missing unity log viewer in link xml

- Editor/ProjectMigration/MigrationModules/ApplovinMigration.cs
> add missing reference

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> add enable collapsible banner status

- Prefabs/NavigationBottomBar/UITemplateBottomNavigatorBar.prefab
- Scripts/Scenes/BottomBarNavigator/UITemplateBottomNavigatorBarView.cs
> upd nav bar

- Editor/Optimization/FontFinderOdin.cs
> disable compress font feature due to not working as expected

- Scripts/Services/AnalyticHandler/UITemplateAnalyticHandler.cs
> fix: missing method

- Scripts/Quests/UITemplateQuestController.cs
> cache, handle redirect target

- Scripts/ThirdPartyServices/AnalyticEvents/Falcon/FalconAnalyticWrapper.cs
- Scripts/UITemplate.Scripts.asmdef
</p>
UI Template
</h1>
Falcon SDK has updated to version 3.0.5 and it no longer had older log services. I change them from FalconAnalyticWrapper
> Update log services for Falcon SDK v3.0.5

- Scripts/Installers/UITemplateInitSignalInstaller.cs
- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
- Scripts/Scenes/Utils/UITemplateCurrencyView.cs
- Scripts/Signals/OnFinishCurrencyAnimationSignal.cs
- Scripts/Signals/OnFinishCurrencyAnimationSignal.cs.meta
> add finish flying animation signal

- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
> if there is no animation attached, just update the currency

- Scripts/FTUE/UITemplateFTUEController.cs
- Scripts/Services/Highlight/HighlightController.cs
- Scripts/Services/Highlight/HighlightElement.cs
> catch adapter handling

- Scripts/ThirdPartyServices/AnalyticEvents/Inwave.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Inwave/InwaveAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Inwave/InwaveAnalyticEventFactory.cs.meta
> add inwave analytic event

- Scripts/Scenes/Utils/UITemplateBlendButton.cs
> Update Base UITemplateBlendButton

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> add log for aoa

- Scripts/Creative/Cheat/TripleTapCheatDetector.cs
> fix cheat tap unscale time

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> hotfix: resolve merge conflict

- Scripts/ThirdPartyServices/AnalyticEvents/Falcon/FalconLocalData.cs
> Add symbol Falcon to remove unused script

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> Capping time counts only while Application is Focusing

- link.xml
> preserve all Newtonsoft.json

- Scripts/Scenes/Main/DailyReward/UITemplateDailyRewardPopupView.cs
> fix: dailyreward popup doesn't autoclose.

- Scripts/ThirdPartyServices/AnalyticEvents/Falcon/FalconAnalyticEventFactory.cs
> resolve IScreenManager in Falcon analytic services

- Scripts/Services/AnalyticHandler/UITemplateAnalyticHandler.cs
> add missing ref in uitemplate analytic handler

- Scripts/UITemplateVContainer.cs
> add symbol DISABLE_LOCK_INPUT

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> feat: implement remote config for AOA Loading threshold

- Scripts/Services/AnalyticHandler/AperoAnalyticHandler.cs
- Scripts/Services/AnalyticHandler/AperoAnalyticHandler.cs.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Apero/AperoAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Apero/Purchase.cs
- Scripts/VContainer/UITemplateAdsVContainer.cs
- Move analytic logic out of analytic factory
> refactor: Apero Analytic event

- Prefabs/NavigationBottomBar/UITemplateBottomNavigatorBar.prefab
> fix: missing prefab in bottom nav bar

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> Disable auto mrec banner

- Scripts/Scenes/EndGame/UITemplateLoseOP2Screen.cs
- Scripts/Scenes/EndGame/UITemplateWinOP2Screen.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> Duymai/native game/show mrec with position

- Scripts/ThirdPartyServices/AnalyticEvents/TheOne/TheOneAnalyticEventFactory.cs
> add theone event

- Scripts/ThirdPartyServices/AnalyticEvents/TheOne/TheOneAnalyticEventFactory.cs
> fix condition

- Scripts/Services/AnalyticHandler/AperoAnalyticHandler.cs
> add preserve attribute

- Scripts/Services/BreakAds/BreakAdsPopupView.cs
> check reward currency break ads popup

- Scripts/Scenes/Popups/UITemplateConnectErrorPopupView.cs
> show no internet popup overlay

- Scripts/Blueprints/UITemplateFTUEBlueprint.cs
> Add json property

- Scripts/FTUE/UITemplateFTUEController.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> Improve FTUE

- Scripts/Blueprints/UITemplateFTUEBlueprint.cs
- Scripts/FTUE/Signal/FTUEShowTooltipSignal.cs
- Scripts/FTUE/UITemplateFTUEController.cs
> Add duration for tooltips of ftue

- Scripts/FTUE/UITemplateFTUESystem.cs
> ftue has duration

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> add THEONE_COLLAPSIBLE_MREC to adservice wrapper

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> fix adservice wrapper creative

- Scripts/Services/CollapsibleMrecService.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> Duc/native game/fix error adservicewrapper creative

- Scripts/Scenes/Popups/UITemplateConnectErrorPopupView.cs
> Check null for model of connect error popup

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> Huydq/native game/hotfix resumeads

- Scripts/FTUE/Conditions/FTUEEnoughCurrencyCondition.cs
- Scripts/FTUE/Conditions/FTUELoseCountCondition.cs
- Scripts/FTUE/Conditions/FTUEPassedLevelCondition.cs
- Scripts/FTUE/Conditions/FtueCondition.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> Sync ftue tooltip text and ftue condition with tooltip presenter

- Scripts/Services/BreakAds/BreakAdsViewHelper.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> delay break ads

- Scripts/FTUE/Signal/FTUEShowTooltipSignal.cs
- Scripts/FTUE/UITemplateFTUEController.cs
> send raw text instead of ftue id

- Scripts/FTUE/UITemplateFTUEVContainer.cs
- Scripts/Models/Controllers/UITemplateFTUEDataController.cs
- Scripts/Models/LocalDatas/UITemplateFTUEData.cs
> Isolate FTUE

- Scripts/FTUE/RemoteConfig/UITemplateFTUEBlueprintDataHandler.cs
- Scripts/FTUE/RemoteConfig/UITemplateFTUERemoteConfig.cs
- Scripts/Models/LocalDatas/UITemplateFTUEData.cs
> fix load blueprint data from remote

- Scripts/Blueprints/UITemplateFTUEBlueprint.cs
- Scripts/FTUE/FTUEListen/FTUEBaseListen.cs
- Scripts/FTUE/Signal/FTUEShowUnlockPopupSignal.cs
- Scripts/FTUE/Signal/FTUEShowUnlockPopupSignal.cs.meta
- Scripts/FTUE/UITemplateFTUESystem.cs
- Scripts/VContainer/UITemplateSignalVContainer.cs
> Update for Showing popup of FTUEs

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
- Scripts/Models/LocalDatas/UITemplateLevelData.cs
- Scripts/Signals/LevelEndedSignal.cs
- Scripts/Signals/LevelSkippedSignal.cs
- Scripts/Signals/LevelStartedSignal.cs
> Update level data

- Scripts/FTUE/Conditions/FTUEEnoughCurrencyCondition.cs
- Scripts/FTUE/Conditions/FTUELoseCountCondition.cs
- Scripts/FTUE/Conditions/FTUEPassedLevelCondition.cs
- Scripts/FTUE/Conditions/FtueCondition.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> Get short condition text

- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
- Scripts/Services/AnalyticHandler/AthenaAnalyticHandler.cs
- Scripts/Services/AnalyticHandler/AthenaAnalyticHandler.cs.meta
- Scripts/Signals/OnUpdateCurrencySignal.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Athena.meta
- Scripts/ThirdPartyServices/AnalyticEvents/Athena/AthenaAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Athena/AthenaAnalyticEventFactory.cs.meta
- Scripts/ThirdPartyServices/AnalyticEvents/BaseAnalyticEventFactory.cs
- Scripts/VContainer/UITemplateAdsVContainer.cs
> [WIP] Athena analytic integration

- Scripts/Services/AnalyticHandler/AthenaAnalyticHandler.cs
> change: pass game mode property

- Scripts/Services/AnalyticHandler/AperoAnalyticHandler.cs
- Scripts/ThirdPartyServices/AnalyticEvents/ABI/ABIAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/AdOne/AdOneAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Amanote/AmanoteAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Apero/AperoAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/BraveStars/BraveStarsAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Crazylab/CrazylabAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Falcon/FalconAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Hapiga/HapigaAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/HiGame/HiGameAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Inwave/InwaveAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Mirai/MiraiAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Rocket/RocketAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Supersonic/SupersonicAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/TheOne/TheOneAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Wido/WidoAnalyticEventFactory.cs
- Scripts/ThirdPartyServices/AnalyticEvents/Zitga/ZitgaAnalyticEventFactory.cs
> change: analytic event factory constructor

- Scripts/FTUE/RemoteConfig/UITemplateFTUEBlueprintDataHandler.cs
> Fix sometimes no data to load

- Scripts/FTUE/Signal/FTUEShowUnlockPopupSignal.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> Add name into ftue unlock signal

- Scripts/Services/AnalyticHandler/UITemplateAnalyticHandler.cs
> update condition to track ad engagement event

- Scripts/Services/AnalyticHandler/BraveStarsAnalyticHandler.cs
> fix constructor BraveStarsAnalyticHandler

- Scripts/Services/Highlight/HighlightController.cs
> refactor HighlightController.cs

- Scripts/FTUE/Conditions/FTUEEnoughCurrencyCondition.cs
- Scripts/FTUE/Conditions/FTUELoseCountCondition.cs
- Scripts/FTUE/Conditions/FTUEPassedLevelCondition.cs
- Scripts/FTUE/Conditions/FtueCondition.cs
- Scripts/FTUE/UITemplateFTUESystem.cs
> Separate trigger condition from pass condition

- Scripts/Models/Controllers/UITemplateInventoryDataController.cs
- Scripts/Services/FlyingAnimation/UITemplateFlyingAnimationController.cs
- Scripts/Signals/PlayCurrencyAnimationSignal.cs
- Scripts/VContainer/UITemplateServicesVContainer.cs
- Scripts/VContainer/UITemplateSignalVContainer.cs
…gister
</p>
UI Template
</h1>
> Fix flying animation controller

- Scripts/Services/Highlight/HighlightController.cs
> Update highlight controller

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> Fix collapsible banner no show when time collap_interval

- Scripts/Configs/GameEvents/NoInternetConfig.cs
> change: no internet default config

- Scripts/Services/AnalyticHandler/AperoAnalyticHandler.cs
> fix: AperoAnalyticHandler constructor

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
> chore: change GetCurrentLevelPlayTime method visibility to public

- Scripts/Scenes/Utils/View/UITemplateCurrencyView.cs
> update currency view

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> can show banner ads

- Scripts/Services/AnalyticHandler/UITemplateAnalyticHandler.cs
> add ad impression engagement 6

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> should show banner ads

- Scripts/Scenes/Utils/View/UITemplateCurrencyView.cs
> update currency when finish animation

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
> update skip level

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
</p>
UI Template
</h1>
Add star count when skipping level
> Skip Level

- Scripts/Services/AnalyticHandler/HiGame/HiGameAnalyticHandler.cs
> update constructor higame analytic

- Editor/ProjectMigration/MigrationModules/PackageMigration/Resources/PackageMigationConfig.json
> update ui effect coffee

- Editor/ProjectMigration/MigrationModules/PackageMigration/Resources/PackageMigationConfig.json
> Lock UIEffect to 5.5.3

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
> Remove unused variable

- Scripts/VContainer/UITemplateThirdPartyVContainer.cs
> hot fix namespace

- Scripts/UITemplateVContainer.cs
- Scripts/VContainer/UITemplateDailyRewardVContainer.cs
> Change register extension name of Daily reward

- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Enum/FpsScreenPosition.cs
- Scripts/Enum/FpsScreenPosition.cs.meta
- Scripts/Scenes/Utils/Fps.cs
- Scripts/Scenes/Utils/Fps.cs.meta
- Scripts/UITemplateVContainer.cs
> add config fps

- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Creative/Cheat/TapOnCornerCheatDetector.cs
- Scripts/Creative/Cheat/TapOnCornerCheatDetector.cs.meta
- Scripts/Creative/Cheat/TheOneCheatView.cs
- Scripts/Enum/TheOneCheatActiveType.cs
Introduced a `TapOnCornerCheatDetector` to detect specific corner-tapping sequences as a cheating method. Updated relevant configurations, enums, and logic to integrate this feature into the cheat detection system.
</p>
UI Template
</h1>
> Add TapOnCorner cheat detection functionality

- Scripts/Models/Controllers/UITemplateLevelDataController.cs
> Add properties to count level per session

- Editor/ProjectMigration/MigrationModules/PackageMigration/Resources/PackageMigationConfig.json
remove force update version ui effect. Because ui effect and true shadow conflict on TMP
> remove force use version ui effect

- Scripts/Services/GameAnalyzer.meta
- Scripts/Services/GameAnalyzer/SessionWatcher.cs
- Scripts/Services/GameAnalyzer/SessionWatcher.cs.meta
- Scripts/Services/GameAnalyzer/SessionWatcherVContainer.cs
- Scripts/Services/GameAnalyzer/SessionWatcherVContainer.cs.meta
- Scripts/UITemplateVContainer.cs
> Session watcher

- Scripts/Scenes/Popups/NativeOverlayInterPopupView.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> Refactor native overlay

- Scripts/Configs/GameEvents/GameFeaturesSetting.cs
- Scripts/Helpers/UITemplateButtonExperienceHelper.cs
> custom button ignore play sound button_click

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapper.cs
> Get number of Inter ad shown this session

- Scripts/ThirdPartyServices/UITemplateAdServiceWrapperCreative.cs
> remove method in creative
